### ISSUE TITLE
Configure trust store

### ISSUE THREAD

**Issue by walt-bb** [sensu/sensu-pagerduty-handler#10]
Hello,
I'm attempting to send pagerduty events via an encrypted proxy.  I am getting this error:
```
{"assets":null,"component":"pipelined","handler":"pagerduty","level":"info","msg":"event pipe handler executed","namespace":"default","output":"Error: Post https://events.pagerduty.com/v2/enqueue: proxyconnect tcp: x509: certificate signed by unknown authority\nUsage:\n  sensu-pagerduty-handler [flags]\n\nFlags:\n  -h, --help           help for sensu-pagerduty-handler\n  -t, --token string   The PagerDuty V2 API authentication token, use default from PAGERDUTY_TOKEN env var (default \"xxx\")\n\nerror: Post https://events.pagerduty.com/v2/enqueue: proxyconnect tcp: x509: certificate signed by unknown authority\n","status":1,"time":"2019-03-08T23:05:06Z"}
```

I believe the problem is that the CA which signed the cert for my proxy is not in the trust store for the sensu-pagerduty-handler.  Is there a way to configure this? If not, please consider this report as a feature-request.

**Comment by walt-bb** [comment]
I was able to workaround this by adding the CA to the OS's trust store.  I added the CA.pem to /etc/ssl/certs and ran "update-ca-certificates --fresh" on debian 9.

**Comment by asachs01** [comment]
Hi @walt-bb , The plugins generally use the the OS store, not handler-specific one., Glad to hear you got it solved.
