### ISSUE TITLE
Feature Request: Support settable dedupe key

### ISSUE THREAD

**Issue by jspaleta** [sensu/sensu-pagerduty-handler#12]
This helps bring the golang handler up to feature parity to the existing community ruby plugin.

**Strawman** 
expose  dedupkey value as a settable via this priority list:
named envvar PAGERDUTY_DEDUP_KEY
cli arg: --dedup-key
named label:  pagerduty.dedup_key

envvar acts as fallback of last resort

named label is used if set

**Label Scopes**
label scope is also prioritied:
agent scope , client scope, handler scope

I'm not sure what label priority order makes the most sense... we should make a decision and make it a best practice for all handlers.

**Comment by fguimond** [comment]
@jspaleta @calebhailey - Would it make sense to also provide the capability to get the deduplication key using a templated argument? As an example the default value which combines the entity name and check name would be equivalent to `{{.Entity.Name}}-{{.Check.Name}}`. Any attribute from the Sensu event would be available and would make for a flexible way of customizing the incident key.

**Comment by echlebek** [comment]
@jspaleta there appears to be PAGERDUTY_DEDUP_KEY in this handler now. Is this issue complete?
