### ISSUE TITLE
Feature Request: allow custom map of event status enum into allowed pagerduty severity

### ISSUE THREAD

**Issue by jspaleta** [sensu/sensu-pagerduty-handler#13]
process a user defined json key,value hash that defines a mapping from integer valued check status, into pagerduty severity strings.  

keys are pagerduty severity strings "info","critical","warning","error"

values are arrays of status values

map example:
`{"info":[130,10],"error":[4]}`
would map status 10 and 130 to "info" and status 4 to "error"

Additionally, if there was a way to encode numeric range that would be fantastic and would lead to very compact representation of complicated status mappings.

**Strawman**

Implement as a commandline switch --status-map
and as entity,check scoped label  ex: `pagerduty.status_map`

**Comment by echlebek** [comment]
@jspaleta similar to the other issue, this flag now appears to exist. Is this issue complete?
