### ISSUE TITLE
What is PAGERDUTY_TOKEN and PAGERDUTY_DEDUP_KEY?

### ISSUE THREAD

**Issue by masifpak** [sensu/sensu-pagerduty-handler#19]
I am using sensugo for monitoring. What following parameter should be.

Mu service name is devstack and team name is devcon.

  

> - PAGERDUTY_TOKEN=76f82173acf040b8a36799bf78b4cbd1 ### Integration API key
>   - PAGERDUTY_DEDUP_KEY=PAGERDUTY_DEDUP_KEY                ### what is this?
>   - PAGERDUTY_DEDUP_KEY_TEMPLATE={{.Entity.Name}}-{{.Check.Name}} . ### what is this?
>   - PAGERDUTY_STATUS_MAP={"info":[130,10],"error":[4]} .   ### what is this?

**Comment by mjiderhamn** [comment]
This is a bug tracker, not a support forum. I'd recommend turning to https://discourse.sensu.io/ or their Slack
