### ISSUE TITLE
Feature Request: Pagerduty EU Datacenter configuration

### ISSUE THREAD

**Issue by solita-mikatormanen** [sensu/sensu-pagerduty-handler#45]
Hello,

According to go-pagerduty maintainer the eu datacenter endpoints are supported but i don't see any mentions of them on this handler. 
https://github.com/PagerDuty/go-pagerduty/issues/355

Could it be possible to include configuration also for eu endpoints?

**Comment by asachs01** [comment]
Hey there @solita-mikatormanen. I believe the fix (#56 ) that @fguimond just implemented may actually support this, as it allows for specifying an alternate endpoint. Can you give this a shot and reopen the issue if it doesn't?
