### ISSUE TITLE
The title of incident without hostname and check name

### ISSUE THREAD

**Issue by pablolibo** [sensu/sensu-pagerduty-handler#5]
Hi all,

I'm having a strange behavior about this handler to pagerduty, when sending the event is not included hostname and the check name of the alert like old version of handler pagerduty written in ruby. 

for example, the ruby version the 'Related to Incident' in pagerduty console is like:

`services-01289.ops/elasticsearch-cluster-status : ESClusterStatus WARNING: Cluster is yellow`
`hostname/check_name: output`

that is fine, but the pagerduty in GO I have something like this: 

`CheckHttp CRITICAL: Request error: end of file reached`
this is the output command without the hostname and check name, I would like to add these fields for a better understanding of the alert.

How I can fix it?

Thanks!

**Comment by pablolibo** [comment]
I am adding new PR for this issue https://github.com/sensu/sensu-pagerduty-handler/pull/6

**Comment by nixwiz** [comment]
This was left open even though changes were merged.  Subsequently, the summary field is now configurable as a template (in #28 )
