### ISSUE TITLE
Feature Request - Pass details template content deserialized to PD

### ISSUE THREAD

**Issue by lspxxv** [sensu/sensu-pagerduty-handler#50]
The PD handler is serializing everything under details template but we want this to be available deserialized in pagerduty.

Json format (when the default payload is sent without -d) can translate to table nicely. We look to be serializing the string with details template producing an undesirable view for the customer.

Config
<img width="820" alt="image" src="https://user-images.githubusercontent.com/37607023/226753095-874325a0-3470-46d6-a78c-6c6693fa4d7f.png">

Event details
<img width="802" alt="image" src="https://user-images.githubusercontent.com/37607023/226753003-f602452e-6798-4a9d-a461-d8df925e8ce1.png">

Introducing functionality like ` -T, --bodyTemplateFile` from the [email handler](https://bonsai.sensu.io/assets/sensu/sensu-email-handler) could be useful here?

Internal ref - https://secure.helpscout.net/conversation/2188359742/31097?folderId=4465878

**Comment by lspxxv** [comment]
@fguimond Any thoughts on this ticket? Its of priority for the customer.

**Comment by fguimond** [comment]
Added the `--details-format=[string|json]` command line option. The default value if missing is `string` which keeps the current behavior where the details are passed as a string. If the value is set to `json` then it will expect the `--details-template` value to be valid JSON and will send that value as a JSON document (as opposed to a string).
