### ISSUE TITLE
Feature Request - Add functionality to allow access to nested keys

### ISSUE THREAD

**Issue by lspxxv** [sensu/sensu-pagerduty-handler#51]
.Entity.labels is available to query, but not values on keys within that, like .entity.labels.malcode in this customers' case below. Sensu docs show the available event attributes [here](https://docs.sensu.io/sensu-go/latest/observability-pipeline/observe-process/handler-templates/#available-event-attributes) but makes no mention of nested attributes.

<img width="817" alt="image" src="https://user-images.githubusercontent.com/37607023/226753605-fbdb02a8-f099-4ed7-9504-743b256c5e1c.png">

internal ref - [here](https://secure.helpscout.net/conversation/2188359742/31097?folderId=4465878)

**Comment by fguimond** [comment]
@lspxxv Unless I misunderstand the request I believe this is already supported as part of the [Go template library](https://pkg.go.dev/text/template) used for template values. Annotation and label values can be queried using the `index` construct: 

* Entity label: `{{index .Entity.Labels "label-key"}}` 
* Event label: `{{index .Labels "label-key"}}`
* Entity annotation: `{{index .Entity.Annotations "annotation-key"}}` 
* Event label: `{{index .Annotations "annotation-key"}}`

**Comment by lspxxv** [comment]
@fguimond you are 100% accurate, the entity example works for this case; i will go ahead close this issue. Thank you!
