### ISSUE TITLE
[Feature Request] Provide ability to specify alternate pagerduty endpoints

### ISSUE THREAD

**Issue by asachs01** [sensu/sensu-pagerduty-handler#54]
In internal ref https://secure.helpscout.net/conversation/2205602449/31243?folderId=5845954, it was noted that other applications sending events to pagerduty have the ability to override the default `events.pagerduty.com` endpoint with a different URL. This is useful in cases where someone is using 3rd party software like the [Pagerduty Alt Agent](https://github.com/martindstone/PDaltagent) to send events to pagerduty. A good example of this is the [Splunk Pagerduty Integration](https://www.pagerduty.com/docs/guides/splunk-integration-guide/). Specifically, it looks like the integration URL there is the kind of feature that should be added.

**Comment by fguimond** [comment]
The latest PagerDuty API does provide the ability to specify an alternate endpoint. The only restriction is that the `/v2/enqueue` path must be available on that endpoint. For example if your alternate endpoint is `http://pd.mycompany.local` the API will send the event to `http://pd.mycompany.local/v2/enqueue`.

**Comment by asachs01** [comment]
@fguimond one of their folks reached out and wrote the code for us: https://gist.github.com/martindstone/72ec38e6281f88942623d4f88d917a97
