### ISSUE TITLE
Feature Request: Support for priority flag

### ISSUE THREAD

**Issue by asachs01** [sensu/sensu-pagerduty-handler#9]
## Expected Behavior
When configuring a check, I should be able to specify the priority of that check in a `"pagerduty"` scope and let pagerduty handle incident priority. 

## Current Behavior
This is not present

## Possible Solution
Allow for configuration of priority in the default pagerduty integration configuration and/or the check/contact level.

**Comment by jspaleta** [comment]
I'm reading the Evvent V2 API and I'm not sure which api element you mean by priority...
https://v2.developer.pagerduty.com/docs/send-an-event-events-api-v2

Are you referring to severity?

**Comment by nixwiz** [comment]
@asachs01 with my PR allowing annotations, could a check annotation that sets the --status-map appropriately work for this use case?

**Comment by asachs01** [comment]
I think this issue is pretty ancient at this point. I'm going to close it out.
